/**
 * Elevation enrichment for routes generated by v1's `generateAIRoutes`.
 *
 * v1's response shape sometimes returns 0 elevation gain when the
 * underlying routing provider (Stadia/Mapbox) doesn't surface it. This
 * helper backfills `stats.elevation_gain_m`/`elevation_loss_m` and a
 * per-point `elevations_m[]` array by calling the same
 * `getElevationData()` helper v1's manual flow uses.
 *
 * Module-level LRU cache (capacity 50) keyed by quantized geometry so
 * the same route doesn't re-fetch elevation on regenerate. No TTL —
 * elevation for a fixed geometry is immutable.
 */

import { getElevationData, calculateElevationStats } from '../../utils/elevation';
import { fnv1a32, stableJson } from '../../routing/RouterClient/cache';
import type { Coordinate, RouteSnapshot } from './types';

interface EnrichedFields {
  elevations_m: number[];
  elevation_gain_m: number;
  elevation_loss_m: number;
}

const CACHE_MAX_SIZE = 50;
const cache = new Map<string, EnrichedFields>();

function cacheGet(key: string): EnrichedFields | null {
  const entry = cache.get(key);
  if (!entry) return null;
  cache.delete(key);
  cache.set(key, entry);
  return entry;
}

function cacheSet(key: string, value: EnrichedFields): void {
  if (cache.has(key)) {
    cache.delete(key);
  } else if (cache.size >= CACHE_MAX_SIZE) {
    const oldest = cache.keys().next().value;
    if (oldest !== undefined) cache.delete(oldest);
  }
  cache.set(key, value);
}

function cacheKeyForGeometry(geometry: ReadonlyArray<Coordinate>): string {
  const quantized = geometry.map(([lng, lat]) => [
    Math.round(lng * 1e5) / 1e5,
    Math.round(lat * 1e5) / 1e5,
  ]);
  return fnv1a32(stableJson(quantized));
}

function isAlreadyEnriched(snap: RouteSnapshot): boolean {
  const hasPositiveGain = (snap.stats?.elevation_gain_m ?? 0) > 0;
  const hasPerPoint =
    Array.isArray(snap.elevations_m) &&
    snap.elevations_m.length === snap.geometry.length;
  return hasPositiveGain && hasPerPoint;
}

export interface EnrichOptions {
  skipCache?: boolean;
}

/**
 * Enrich a single route snapshot with API-derived elevation. Pure
 * pass-through for already-enriched or degenerate-geometry routes.
 * Never throws — on API failure, returns the input unchanged.
 */
export async function enrichRouteElevation(
  snap: RouteSnapshot,
  options: EnrichOptions = {},
): Promise<RouteSnapshot> {
  const geometry = snap.geometry;
  if (!Array.isArray(geometry) || geometry.length < 2) return snap;
  if (isAlreadyEnriched(snap)) return snap;

  const key = cacheKeyForGeometry(geometry);
  if (!options.skipCache) {
    const cached = cacheGet(key);
    if (cached) return mergeEnriched(snap, cached);
  }

  try {
    const profile = await getElevationData(geometry as Array<[number, number]>);
    if (!profile || !Array.isArray(profile) || profile.length === 0) return snap;
    if (profile.length !== geometry.length) return snap;

    const stats = calculateElevationStats(profile);
    const enriched: EnrichedFields = {
      elevations_m: profile.map((p: { elevation: number }) => p.elevation),
      elevation_gain_m: stats.gain,
      elevation_loss_m: stats.loss,
    };
    cacheSet(key, enriched);
    return mergeEnriched(snap, enriched);
  } catch {
    return snap;
  }
}

function mergeEnriched(snap: RouteSnapshot, enriched: EnrichedFields): RouteSnapshot {
  return {
    ...snap,
    stats: {
      ...snap.stats,
      elevation_gain_m: enriched.elevation_gain_m,
      elevation_loss_m: enriched.elevation_loss_m,
    },
    elevations_m: enriched.elevations_m,
  };
}

export function clearElevationCache(): void {
  cache.clear();
}
