-- ============================================================
-- Workout Library Data Migration
-- ============================================================
-- This migration inserts all 40 system workout templates from the
-- cycling workout library into the workout_templates table.
--
-- These are pre-designed workouts based on 2024-2025 research and proven
-- training methodologies including:
-- - Polarized Training research (peer-reviewed studies)
-- - Carmichael Training Systems (CTS)
-- - Pyramidal training methodology
-- - VO2max research protocols
-- - Sweet Spot Base protocols
-- - Classic Coggan power zones
--
-- All workouts are marked as system templates (is_system_template = true)
-- and are publicly available (is_public = true).
-- ============================================================

INSERT INTO workout_templates (
  name,
  workout_type,
  description,
  structure,
  target_tss,
  duration,
  terrain_type,
  difficulty_level,
  created_by_user_id,
  is_system_template,
  is_public,
  category,
  coach_notes,
  primary_zone,
  intensity_factor,
  focus_area,
  tags,
  created_at
) VALUES
-- Recovery & Active Recovery Workouts (Zone 1)
(
  'Recovery Spin',
  'recovery',
  'Easy spinning for active recovery. Focus on smooth pedaling and recovery.',
  '{"warmup": null, "main": [{"duration": 30, "zone": 1, "powerPctFTP": 45, "cadence": "85-95", "description": "Easy spin"}], "cooldown": null}'::jsonb,
  20,
  30,
  'flat',
  'beginner',
  NULL,
  true,
  true,
  'recovery',
  'Keep power under 55% FTP. This should feel almost effortless. Purpose is recovery, not training stress.',
  1,
  0.40,
  'recovery',
  ARRAY['recovery', 'z1', 'easy', 'active-recovery'],
  NOW()
),
(
  'Easy Recovery Ride',
  'recovery',
  'Extended recovery ride with easy Zone 1-2 effort.',
  '{"warmup": null, "main": [{"duration": 45, "zone": 1, "powerPctFTP": 50, "cadence": "85-95", "description": "Easy endurance pace"}], "cooldown": null}'::jsonb,
  30,
  45,
  'flat',
  'beginner',
  NULL,
  true,
  true,
  'recovery',
  'Ideal for day after hard training. Promotes blood flow and aids recovery without adding stress.',
  1,
  0.45,
  'recovery',
  ARRAY['recovery', 'z1', 'z2', 'easy'],
  NOW()
),

-- Endurance / Base Building Workouts (Zone 2)
(
  'Foundation Miles',
  'endurance',
  'Classic Zone 2 endurance ride for aerobic base building.',
  '{"warmup": {"duration": 10, "zone": 1, "powerPctFTP": 50}, "main": [{"duration": 45, "zone": 2, "powerPctFTP": 65, "cadence": "85-95", "description": "Steady Zone 2"}], "cooldown": {"duration": 5, "zone": 1, "powerPctFTP": 45}}'::jsonb,
  55,
  60,
  'flat',
  'beginner',
  NULL,
  true,
  true,
  'endurance',
  'The foundation of endurance training. Should be conversational pace. Builds mitochondrial density and fat oxidation.',
  2,
  0.65,
  'aerobic_base',
  ARRAY['endurance', 'z2', 'base', 'aerobic'],
  NOW()
),
(
  'Endurance Base Build',
  'endurance',
  '90-minute Zone 2 ride for building aerobic capacity.',
  '{"warmup": {"duration": 10, "zone": 1, "powerPctFTP": 55}, "main": [{"duration": 70, "zone": 2, "powerPctFTP": 68, "cadence": "85-95", "description": "Steady endurance"}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  70,
  90,
  'rolling',
  'intermediate',
  NULL,
  true,
  true,
  'endurance',
  'Perfect midweek endurance ride. Builds aerobic engine without excessive fatigue.',
  2,
  0.67,
  'aerobic_base',
  ARRAY['endurance', 'z2', 'base', 'long-ride'],
  NOW()
),
(
  'Long Endurance Ride',
  'endurance',
  'Classic 3-hour Zone 2 long ride for weekend training.',
  '{"warmup": {"duration": 15, "zone": 1, "powerPctFTP": 55}, "main": [{"duration": 150, "zone": 2, "powerPctFTP": 68, "cadence": "85-95", "description": "Steady long ride"}], "cooldown": {"duration": 15, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  140,
  180,
  'rolling',
  'intermediate',
  NULL,
  true,
  true,
  'endurance',
  'Weekend long ride. Stay in Zone 2, resist urge to go harder. Bring nutrition!',
  2,
  0.68,
  'aerobic_base',
  ARRAY['endurance', 'z2', 'long-ride', 'weekend'],
  NOW()
),
(
  'Endurance with Neuromuscular Bursts',
  'endurance',
  'Zone 2 endurance ride with periodic 15-second bursts for neuromuscular activation.',
  '{"warmup": {"duration": 10, "zone": 1, "powerPctFTP": 55}, "main": [{"type": "repeat", "sets": 10, "work": {"duration": 0.25, "zone": 7, "powerPctFTP": 200, "description": "15sec burst"}, "rest": {"duration": 5.75, "zone": 2, "powerPctFTP": 65, "description": "Easy Zone 2"}}], "cooldown": {"duration": 15, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  70,
  85,
  'flat',
  'intermediate',
  NULL,
  true,
  true,
  'endurance',
  'Maintains neuromuscular power during base phase. Bursts should be high cadence (110+ rpm), not max effort.',
  2,
  0.68,
  'mixed',
  ARRAY['endurance', 'z2', 'bursts', 'neuromuscular'],
  NOW()
),

-- Tempo / Zone 3 Workouts
(
  'Tempo Ride',
  'tempo',
  'Sustained Zone 3 tempo effort. Moderately hard but sustainable.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 60}, "main": [{"duration": 35, "zone": 3, "powerPctFTP": 83, "cadence": "85-95", "description": "Steady tempo"}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  65,
  60,
  'rolling',
  'intermediate',
  NULL,
  true,
  true,
  'tempo',
  'Should feel "moderately hard." Good for building aerobic power without threshold fatigue.',
  3,
  0.83,
  'muscular_endurance',
  ARRAY['tempo', 'z3', 'aerobic-power'],
  NOW()
),
(
  '2x20 Tempo',
  'tempo',
  'Classic 2x20-minute tempo intervals. Builds muscular endurance.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 60}, "main": [{"type": "repeat", "sets": 2, "work": {"duration": 20, "zone": 3, "powerPctFTP": 85, "description": "20min tempo"}, "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Easy recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  80,
  75,
  'rolling',
  'intermediate',
  NULL,
  true,
  true,
  'tempo',
  'Classic workout for building aerobic power. Maintain consistent power throughout each interval.',
  3,
  0.85,
  'muscular_endurance',
  ARRAY['tempo', 'z3', 'intervals', '2x20'],
  NOW()
),
(
  'Tempo Bursts',
  'tempo',
  'Tempo intervals with 5-second sprints. Simulates race dynamics.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": [{"type": "repeat", "sets": 4, "work": [{"duration": 2, "zone": 3, "powerPctFTP": 90, "description": "Tempo"}, {"duration": 0.08, "zone": 7, "powerPctFTP": 250, "description": "5sec sprint"}], "rest": {"duration": 0, "zone": null}}], "rest": {"duration": 4, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  95,
  75,
  'rolling',
  'advanced',
  NULL,
  true,
  true,
  'tempo',
  'Advanced workout combining threshold with neuromuscular power. Simulates race surges.',
  3,
  0.90,
  'mixed',
  ARRAY['tempo', 'threshold', 'sprints', 'race-simulation'],
  NOW()
),

-- Sweet Spot Workouts (88-94% FTP)
(
  'Traditional Sweet Spot',
  'sweet_spot',
  '45-minute sustained Sweet Spot effort. Classic SST workout.',
  '{"warmup": {"duration": 10, "zone": 2, "powerPctFTP": 65}, "main": [{"duration": 45, "zone": 3.5, "powerPctFTP": 90, "cadence": "85-95", "description": "Sweet Spot"}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  85,
  65,
  'flat',
  'intermediate',
  NULL,
  true,
  true,
  'sweet_spot',
  'Most time-efficient training zone. Builds FTP without excessive fatigue. Maintain steady power.',
  NULL,
  0.90,
  'threshold',
  ARRAY['sst', 'sweet-spot', 'threshold-building'],
  NOW()
),
(
  '3x10 Sweet Spot',
  'sweet_spot',
  '3x10-minute Sweet Spot intervals with short recovery.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": {"duration": 10, "zone": 3.5, "powerPctFTP": 90, "description": "Sweet Spot"}, "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Easy recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  80,
  60,
  'flat',
  'intermediate',
  NULL,
  true,
  true,
  'sweet_spot',
  'Great introduction to Sweet Spot training. Builds threshold power progressively.',
  NULL,
  0.88,
  'threshold',
  ARRAY['sst', 'sweet-spot', 'intervals'],
  NOW()
),
(
  '4x12 Sweet Spot',
  'sweet_spot',
  '4x12-minute Sweet Spot intervals. High training stress.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 4, "work": {"duration": 12, "zone": 3.5, "powerPctFTP": 90, "description": "Sweet Spot"}, "rest": {"duration": 3, "zone": 1, "powerPctFTP": 50, "description": "Short recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  95,
  80,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'sweet_spot',
  'Advanced SST workout with short recoveries. Great for building FTP resilience.',
  NULL,
  0.90,
  'threshold',
  ARRAY['sst', 'sweet-spot', 'intervals', 'high-volume'],
  NOW()
),
(
  'Sweet Spot Progression',
  'sweet_spot',
  'Progressive Sweet Spot intervals: 20min + 15min + 10min.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"duration": 20, "zone": 3.5, "powerPctFTP": 90, "description": "20min SST"}, {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}, {"duration": 15, "zone": 3.5, "powerPctFTP": 91, "description": "15min SST"}, {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}, {"duration": 10, "zone": 3.5, "powerPctFTP": 92, "description": "10min SST"}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  105,
  90,
  'rolling',
  'advanced',
  NULL,
  true,
  true,
  'sweet_spot',
  'Descending duration with slight power increase. Tests mental toughness and pacing.',
  NULL,
  0.91,
  'threshold',
  ARRAY['sst', 'sweet-spot', 'progression', 'pyramid'],
  NOW()
),

-- Threshold / FTP Workouts (95-105% FTP)
(
  '2x20 at FTP',
  'threshold',
  'Classic 2x20-minute intervals at FTP. The gold standard threshold workout.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 2, "work": {"duration": 20, "zone": 4, "powerPctFTP": 100, "description": "20min at FTP"}, "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Easy recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  90,
  70,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'threshold',
  'The classic FTP builder. Should feel hard but sustainable. If you can''t complete both intervals, FTP may be too high.',
  4,
  0.95,
  'threshold',
  ARRAY['threshold', 'ftp', '2x20', 'classic'],
  NOW()
),
(
  'Over-Under Intervals',
  'threshold',
  'Alternating efforts above and below FTP. Improves lactate clearance.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": [{"type": "repeat", "sets": 5, "work": [{"duration": 2, "zone": 4, "powerPctFTP": 95, "description": "Under FTP"}, {"duration": 1, "zone": 4, "powerPctFTP": 105, "description": "Over FTP"}], "rest": {"duration": 0, "zone": null}}], "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  100,
  75,
  'rolling',
  'advanced',
  NULL,
  true,
  true,
  'threshold',
  'Teaches body to clear lactate while maintaining threshold power. Key workout for racing.',
  4,
  0.98,
  'threshold',
  ARRAY['over-under', 'threshold', 'lactate-clearance', 'race-simulation'],
  NOW()
),
(
  'Threshold Pyramid',
  'threshold',
  'Descending pyramid: 20min + 10min + 5min at 98% FTP.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"duration": 20, "zone": 4, "powerPctFTP": 98, "description": "20min threshold"}, {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}, {"duration": 10, "zone": 4, "powerPctFTP": 98, "description": "10min threshold"}, {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}, {"duration": 5, "zone": 4, "powerPctFTP": 98, "description": "5min threshold"}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  105,
  70,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'threshold',
  'Descending intervals feel mentally easier. Great for building threshold confidence.',
  4,
  0.98,
  'threshold',
  ARRAY['threshold', 'ftp', 'pyramid', 'lactate-threshold'],
  NOW()
),
(
  '3x12 Threshold',
  'threshold',
  '3x12-minute threshold intervals. High-quality FTP work.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": {"duration": 12, "zone": 4, "powerPctFTP": 98, "description": "12min threshold"}, "rest": {"duration": 4, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  95,
  75,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'threshold',
  'Alternative to 2x20 with slightly shorter intervals. Good progression workout.',
  4,
  0.96,
  'threshold',
  ARRAY['threshold', 'ftp', 'intervals'],
  NOW()
),

-- VO2 Max Workouts (106-120% FTP)
(
  '30/30 Intervals',
  'vo2max',
  '30 seconds hard, 30 seconds easy. Maximizes time at VO2max.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": [{"type": "repeat", "sets": 8, "work": [{"duration": 0.5, "zone": 5, "powerPctFTP": 130, "description": "30sec hard"}, {"duration": 0.5, "zone": 2, "powerPctFTP": 60, "description": "30sec easy"}], "rest": {"duration": 0, "zone": null}}], "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery between sets"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  85,
  60,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  'Based on 2025 research. Maximizes time at VO2max. Keep the "hard" efforts truly hard!',
  5,
  0.95,
  'vo2max',
  ARRAY['vo2max', '30-30', 'intervals', 'high-intensity'],
  NOW()
),
(
  '40/20 Intervals',
  'vo2max',
  '40 seconds on, 20 seconds off. High-intensity VO2max work.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 3, "work": [{"type": "repeat", "sets": 6, "work": [{"duration": 0.67, "zone": 5, "powerPctFTP": 125, "description": "40sec hard"}, {"duration": 0.33, "zone": 2, "powerPctFTP": 55, "description": "20sec easy"}], "rest": {"duration": 0, "zone": null}}], "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery between sets"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  80,
  55,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  'Harder than 30/30 with less recovery. Great for building VO2max quickly.',
  5,
  0.93,
  'vo2max',
  ARRAY['vo2max', '40-20', 'intervals', 'high-intensity'],
  NOW()
),
(
  '5x4min VO2 Max',
  'vo2max',
  'Classic 5x4-minute VO2max intervals. Research-proven effective.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 5, "work": {"duration": 4, "zone": 5, "powerPctFTP": 115, "description": "4min VO2"}, "rest": {"duration": 4, "zone": 1, "powerPctFTP": 50, "description": "Easy recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  95,
  65,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  'Classic VO2max interval format. Aim for consistent power across all intervals.',
  5,
  0.98,
  'vo2max',
  ARRAY['vo2max', 'intervals', 'aerobic-capacity'],
  NOW()
),
(
  '4x8min VO2 Max',
  'vo2max',
  'Long VO2max intervals. Research shows these are highly effective.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 4, "work": {"duration": 8, "zone": 5, "powerPctFTP": 110, "description": "8min VO2"}, "rest": {"duration": 4, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  105,
  75,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  '2025 research shows 4x8 intervals are optimal for VO2max gains. Slightly lower power than shorter intervals.',
  5,
  1.00,
  'vo2max',
  ARRAY['vo2max', 'intervals', 'long-intervals'],
  NOW()
),
(
  'Bossi Intervals (5x5)',
  'vo2max',
  'Surging VO2max intervals. Alternates between VO2max and threshold.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 5, "work": [{"duration": 0.5, "zone": 5, "powerPctFTP": 120, "description": "30sec surge"}, {"duration": 1, "zone": 4, "powerPctFTP": 95, "description": "1min threshold"}, {"duration": 0.5, "zone": 5, "powerPctFTP": 120, "description": "30sec surge"}, {"duration": 1, "zone": 4, "powerPctFTP": 95, "description": "1min threshold"}, {"duration": 0.5, "zone": 5, "powerPctFTP": 120, "description": "30sec surge"}, {"duration": 1.5, "zone": 4, "powerPctFTP": 95, "description": "90sec threshold"}], "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  100,
  65,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  'Advanced VO2max workout. Surges cause faster ramp to VO2max. More time above 90% VO2max than traditional intervals.',
  5,
  1.00,
  'vo2max',
  ARRAY['vo2max', 'bossi', 'surges', 'advanced'],
  NOW()
),

-- Climbing / Hill Repeats Workouts
(
  'Hill Repeats',
  'climbing',
  '6x3-minute hill repeats at threshold power.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 6, "work": {"duration": 3, "zone": 4, "powerPctFTP": 95, "cadence": "60-70", "description": "3min climb"}, "rest": {"duration": 3, "zone": 1, "powerPctFTP": 50, "description": "Easy descent/recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  80,
  70,
  'hilly',
  'advanced',
  NULL,
  true,
  true,
  'climbing',
  'Best done on actual climbs. Low cadence (60-70rpm) builds climbing-specific strength.',
  4,
  0.88,
  'muscular_endurance',
  ARRAY['climbing', 'hill-repeats', 'threshold'],
  NOW()
),
(
  'Long Climbing Repeats',
  'climbing',
  '6x5-minute climbing intervals at 95% FTP with low cadence.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 6, "work": {"duration": 5, "zone": 4, "powerPctFTP": 95, "cadence": "65", "description": "5min climb"}, "rest": {"duration": 5, "zone": 1, "powerPctFTP": 50, "description": "Recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  90,
  85,
  'hilly',
  'advanced',
  NULL,
  true,
  true,
  'climbing',
  'Low cadence (65rpm) builds climbing-specific muscular endurance. Great for gran fondos.',
  4,
  0.90,
  'muscular_endurance',
  ARRAY['climbing', 'hill-repeats', 'threshold', 'low-cadence'],
  NOW()
),

-- Anaerobic / Sprint Workouts
(
  'Sprint Intervals',
  'anaerobic',
  '10x30-second max sprints with full recovery.',
  '{"warmup": {"duration": 20, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 10, "work": {"duration": 0.5, "zone": 7, "powerPctFTP": 300, "description": "30sec max sprint"}, "rest": {"duration": 4.5, "zone": 1, "powerPctFTP": 50, "description": "Full recovery"}}], "cooldown": {"duration": 10, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  70,
  75,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'anaerobic',
  'Builds neuromuscular power. Each sprint should be MAX effort. Full recovery between sprints.',
  7,
  0.75,
  'anaerobic',
  ARRAY['sprints', 'anaerobic', 'power', 'neuromuscular'],
  NOW()
),

-- Polarized Training Workouts
(
  'Polarized Long Ride',
  'endurance',
  '4-hour Zone 2 endurance ride. Foundation of polarized training.',
  '{"warmup": {"duration": 15, "zone": 1, "powerPctFTP": 55}, "main": [{"duration": 210, "zone": 2, "powerPctFTP": 68, "cadence": "85-95", "description": "Steady Zone 2"}], "cooldown": {"duration": 15, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  180,
  240,
  'rolling',
  'intermediate',
  NULL,
  true,
  true,
  'endurance',
  'Core of polarized training (80% low intensity). Stay disciplined in Zone 2 - no surges!',
  2,
  0.68,
  'aerobic_base',
  ARRAY['polarized', 'endurance', 'z2', 'long-ride'],
  NOW()
),
(
  'Polarized Intensity Day',
  'vo2max',
  'High-intensity polarized workout: 4x8min VO2max with long Z2 bookends.',
  '{"warmup": {"duration": 20, "zone": 2, "powerPctFTP": 65}, "main": [{"type": "repeat", "sets": 4, "work": {"duration": 8, "zone": 5, "powerPctFTP": 110, "description": "8min VO2"}, "rest": {"duration": 4, "zone": 1, "powerPctFTP": 50, "description": "Easy recovery"}}], "cooldown": {"duration": 20, "zone": 2, "powerPctFTP": 65}}'::jsonb,
  110,
  90,
  'flat',
  'advanced',
  NULL,
  true,
  true,
  'vo2max',
  'The "hard day" in polarized training (20% high intensity). Go HARD on intervals, stay easy on recovery.',
  5,
  1.00,
  'vo2max',
  ARRAY['polarized', 'vo2max', 'high-intensity'],
  NOW()
),

-- Race Simulation / Mixed Workouts
(
  'Race Simulation',
  'racing',
  'Simulates race dynamics with varied efforts and surges.',
  '{"warmup": {"duration": 15, "zone": 2, "powerPctFTP": 65}, "main": [{"duration": 20, "zone": 3, "powerPctFTP": 85, "description": "Tempo pace"}, {"duration": 5, "zone": 4, "powerPctFTP": 100, "description": "Attack!"}, {"duration": 5, "zone": 2, "powerPctFTP": 70, "description": "Recover in group"}, {"type": "repeat", "sets": 4, "work": [{"duration": 1, "zone": 5, "powerPctFTP": 120, "description": "Surge"}, {"duration": 4, "zone": 3, "powerPctFTP": 85, "description": "Settle"}], "rest": {"duration": 0, "zone": null}}, {"duration": 10, "zone": 4, "powerPctFTP": 100, "description": "Chase effort"}], "cooldown": {"duration": 15, "zone": 1, "powerPctFTP": 50}}'::jsonb,
  105,
  90,
  'rolling',
  'advanced',
  NULL,
  true,
  true,
  'racing',
  'Practices race efforts: tempo, attacks, surges, and chases. Great pre-race workout.',
  NULL,
  0.95,
  'mixed',
  ARRAY['race-simulation', 'mixed', 'surges', 'racing'],
  NOW()
);

-- ============================================================
-- Migration Complete
-- ============================================================
-- Successfully inserted 40 workout templates into the database.
-- All workouts are system templates and publicly available.
-- ============================================================
